export const LEVELS = [
  {
    level: 1,
    targetDistance: 650,
    speed: 35,
    curvature: 2,
    obstacleChance: 0.15,
    starCount: 1,
  },
  {
    level: 2,
    targetDistance: 1000,
    speed: 40,
    curvature: 2.5,
    obstacleChance: 0.25,
    starCount: 2,
  },
  {
    level: 3,
    targetDistance: 1500,
    speed: 45,
    curvature: 3,
    obstacleChance: 0.30,
    starCount: 3,
  },
  {
    level: 4,
    targetDistance: 2000,
    speed: 48,
    curvature: 3.5,
    obstacleChance: 0.40,
    starCount: 4,
  },
  {
    level: 5,
    targetDistance: 2500,
    speed: 53,
    curvature: 4,
    obstacleChance: 0.48,
    starCount: 5,
  },
  {
    level: 6,
    targetDistance: 3000,
    speed: 59,
    curvature: 4.5,
    obstacleChance: 0.55,
    starCount: 6,
  },
  {
    level: 7,
    targetDistance: 3800,
    speed: 65,
    curvature: 5,
    obstacleChance: 0.75,
    starCount: 7,
  },
];
